repos:
  - repo: https://github.com/FeryET/pre-commit-rust
    rev: v1.2.1
    hooks:
      - id: fmt
        args: ["--edition", "2021", "--"]
      - id: cargo-check
      - id: clippy
        args: ["--all-targets", "--all-features", "--", "-D", "warnings"]
      - id: test
        stages: [pre-push]
